version: "3.9"

services:
  postgres:
    image: postgres:18-alpine
    container_name: auth-factor-qr-postgres
    environment:
      POSTGRES_DB: auth_factor_qr
      POSTGRES_USER: auth_factor_qr
      POSTGRES_PASSWORD: auth_factor_qr
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: