package ru.mephi.abondarenko.auth.factor.qr.domain

enum class AuditEventType {
    ENROLLMENT_STARTED,
    ENROLLMENT_CONFIRMED,
    ENROLLMENT_CONFIRM_FAILED,
    DEVICE_REVOKED,
    AUTH_CHALLENGE_CREATED,
    AUTH_CHALLENGE_RATE_LIMITED,
    AUTH_RESPONSE_APPROVED,
    AUTH_RESPONSE_REJECTED,
    AUTH_VERIFY_RATE_LIMITED,
    AUTH_SESSION_EXPIRED,
    AUTH_SESSION_BLOCKED
}
