spring:
  jpa:
    hibernate:
      ddl-auto: create-drop

  flyway:
    enabled: false

app:
  auth-factor:
    debug-ui-enabled: true
    demo-ui-enabled: true
    enrollment-token-ttl: 10m
    device-response-token-ttl: 2m
    master-key-base64: MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=
    api-key: dev-api-key
